-- DROP TABLE BATCH IF EXISTS;

CREATE TABLE IF NOT EXISTS BATCH  (
    id int(10) AUTO_INCREMENT NOT NULL,
    field1 VARCHAR(40),
    field2 VARCHAR(40),
    field3 VARCHAR(80),
    field4 VARCHAR(40),
    PRIMARY KEY(id)
);
